### ISSUE TITLE
Camera option not working

### ISSUE THREAD

**Issue by Pranoyenjamuri** [ravi8x/Android-Image-Picker-and-Cropping#2]
After capturing an image from "Take camera", it redirects to the camera - not going further to crop image screen.

**Comment by ravi8x** [comment]
Any errors in your LogCat?

**Comment by littledreamlittledev** [comment]
Try to add

List<ResolveInfo> resolvedIntentActivities = ImagePickerActivity.this.getPackageManager()
                                    .queryIntentActivities(takePictureIntent, PackageManager.MATCH_DEFAULT_ONLY);
                            for (ResolveInfo resolvedIntentInfo : resolvedIntentActivities) {
                                String packageName = resolvedIntentInfo.activityInfo.packageName;
                                ImagePickerActivity.this.grantUriPermission(packageName, getCacheImagePath(fileName), FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
                            }

After takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, getCacheImagePath(fileName));
In takeCameraImage method

**Comment by heons** [comment]
Ucrop is supporting Android from Honeycomb (API 11) to Pie (API 28). You could check your API version. It happened for me as well but with Gallery not with Camera.

**Comment by anorouzi** [comment]
First You have done a great work thanks.
And the problem:
It is also happening for gallery. simply it reconstruct the activity even in the sample not using it as library. for some images this happen. 
fro recreating the error you put an image inside memory of mobile. then select it. the got got app and select another image from sd card. (try to use images with different aspect ratio). It is also happening for camera select.
till now i couldn't find any solution for maybe t is from ucrop library ! maybe!!

Window went away: Window{b745388 u0 /com.yalantis.ucrop.UCropActivity}
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.exifinterface.media.ExifInterface$1>

**Comment by AppuAdarsh** [comment]
I am facing the above probelm: Please help me 

 E/BitmapWorkerTask: Copying failed
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at androidx.core.content.FileProvider.openFile(FileProvider.java:566)
        at android.content.ContentProvider.openAssetFile(ContentProvider.java:1561)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1741)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1807)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:425)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1425)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1262)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:982)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:210)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-07-27 00:59:33.873 30079-30079/com.appuzzcreations.update E/TransformImageView: onFailure: setImageUri
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
        at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
        at androidx.core.content.FileProvider.openFile(FileProvider.java:566)
        at android.content.ContentProvider.openAssetFile(ContentProvider.java:1561)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1741)
        at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1807)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:425)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1425)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1262)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:982)
        at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:210)
        at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
